### ISSUE TITLE
Reproduce Table 3

### ISSUE THREAD

**Issue by sigeisler** [fundamentalvision/Deformable-DETR#12]
Hi,

First, I want to thank you to provide your code despite the migration from your internal codebase.

I am wondering what I need to do to reproduce the state-of-the-art results in Table 3. Either I missed sth or you do not explain this in your readme.

It would be awesome if you could give some pointer and maybe even provide a pre-trained model.

Thanks,
Simon

**Comment by jackroos** [comment]
Hi @sigeisler  

Thanks for your interest. Due to the platform switch, the previous pre-trained models could not be used in this codebase, we may train some larger models (e.g., ResNet 101) and release them in the future. But for now, you should train them by yourself. For ResNet 101, you could simply add the '--backbone resnet101' argument in [this config file](https://github.com/fundamentalvision/Deformable-DETR/blob/main/configs/r50_deformable_detr_plus_iterative_bbox_refinement_plus_plus_two_stage.sh). For ResNeXt and DCN, we don't support them now in this codebase, you should modify the backbone file by yourself. Thank you!

**Comment by sigeisler** [comment]
Hi @jackroos 

thank you very much! Brief follow-up question. I noticed that in contrast to DETR you increased the number of object queries from 100 to 300. How much is the performance boost of doing that? Was there any specific reason why you increased this?

**Comment by mordechail** [comment]
Hi,

ResNet 101/ResNeXt models will be released soon?
