### ISSUE TITLE
Why is the classification cost  in matcher formulated as the positive minus negative?

### ISSUE THREAD

**Issue by Godricly** [fundamentalvision/Deformable-DETR#200]
Hi, I'm confused with this part. The computation here is different from the implementation in sigmoid_focal_loss computation. What is the purpose here to use minus sign?
https://github.com/fundamentalvision/Deformable-DETR/blob/11169a60c33333af00a4849f1808023eba96a931/models/matcher.py#L81

**Comment by Godricly** [comment]
found an explaination in https://arxiv.org/pdf/2304.04742.pdf.

**Comment by jacksonsc007** [comment]
In the later stages of training, sample candidates tend to have classification scores close to 1. If we only consider the positive term, the class cost deviation between candidates might be too small to distinguish their superiority. As a result, the total cost is dominated by box cost, due to fixed rigid coefficients in the cost function. By introducing the negative term, we can scale up the class cost, allowing for better differentiation. (Insights and answers from [this issue](https://github.com/IDEA-Research/DINO/issues/139#:~:text=The%20good%20thing%20of%20focal%20cost%20is%20that%20it%20is%20very%20sensitive%20when%20p%20is%20close%20to%200%20or%201%2C%20meaning%20class%20will%20be%20matched%20better%20in%20later%20stages.))


![image](https://github.com/user-attachments/assets/7ecac2b7-47a8-461c-bb31-a4629620b430)
